set(_AMENT_PACKAGE_NAME "orbslam")
set(orbslam_VERSION "0.0.1")
set(orbslam_MAINTAINER "Alberto Soragna <alberto.soragna@gmail.com>")
set(orbslam_BUILD_DEPENDS "rclcpp" "sensor_msgs" "visualization_msgs" "cv_bridge" "message_filters")
set(orbslam_BUILDTOOL_DEPENDS "ament_cmake")
set(orbslam_BUILD_EXPORT_DEPENDS )
set(orbslam_BUILDTOOL_EXPORT_DEPENDS )
set(orbslam_EXEC_DEPENDS "rclcpp" "sensor_msgs" "visualization_msgs" "cv_bridge" "message_filters")
set(orbslam_TEST_DEPENDS )
set(orbslam_GROUP_DEPENDS )
set(orbslam_MEMBER_OF_GROUPS )
set(orbslam_DEPRECATED "")
set(orbslam_EXPORT_TAGS)
list(APPEND orbslam_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
