FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV HOME=/root
ENV ROS_DISTRO=jazzy
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

WORKDIR $HOME
SHELL ["/bin/bash", "-c"]

ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=graphics

RUN apt-get update && apt-get install -y \
    build-essential \
    ca-certificates \
    clang-format \
    cmake \
    curl \
    git \
    gnupg \
    ipython3 \
    locales \
    nano \
    python3-dev \
    python3-numpy \
    python3-pip \
    software-properties-common \
    vim \
    wget && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

RUN add-apt-repository universe && \
    apt-get update && \
    apt-get install -y curl && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb \
      "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo ${UBUNTU_CODENAME:-${VERSION_CODENAME}})_all.deb" && \
    dpkg -i /tmp/ros2-apt-source.deb && \
    rm -f /tmp/ros2-apt-source.deb && \
    apt-get update

RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    ros-dev-tools \
    ros-jazzy-desktop && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    python3-argcomplete \
    python3-coverage \
    python3-flake8 \
    python3-pip \
    python3-pluggy \
    python3-pytest \
    python3-pytest-cov \
    python3-pytest-repeat \
    python3-pytest-rerunfailures \
    python3-rospkg-modules \
    python3-setuptools \
    python3-wheel && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --break-system-packages \
    flake8-blind-except \
    flake8-builtins \
    flake8-class-newline \
    flake8-comprehensions \
    flake8-deprecated \
    flake8-docstrings \
    flake8-import-order \
    flake8-quotes \
    pytest-runner

RUN if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then rosdep init; fi && \
    rosdep update

RUN apt-get update && apt-get install -y \
    libavcodec-dev \
    libavformat-dev \
    libboost-all-dev \
    libboost-system-dev \
    libcanberra-gtk-module \
    libdc1394-dev \
    libeigen3-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libgtk2.0-dev \
    libjpeg-dev \
    libpng-dev \
    libswscale-dev \
    libtbb-dev \
    libtbbmalloc2 \
    libtiff-dev \
    pkg-config && \
    rm -rf /var/lib/apt/lists/*

RUN git clone -b 3.4 https://github.com/opencv/opencv.git $HOME/opencv && \
    mkdir -p $HOME/opencv/build
WORKDIR $HOME/opencv/build

COPY scripts/build_opencv.sh $HOME/scripts/build_opencv.sh
RUN chmod +x $HOME/scripts/build_opencv.sh && \
    bash $HOME/scripts/build_opencv.sh

ADD https://api.github.com/repos/alsora/ORB_SLAM2/git/refs/heads/master version.json
RUN git clone --recurse-submodules https://github.com/alsora/ORB_SLAM2.git $HOME/ORB_SLAM2

WORKDIR $HOME/ORB_SLAM2/ros2-ORB_SLAM2
RUN git checkout orbslam_dev && \
    sed -i 's#<cv_bridge/cv_bridge.h>#<cv_bridge/cv_bridge.hpp>#g' \
      src/monocular/monocular-slam-node.hpp \
      src/rgbd/rgbd.cpp

WORKDIR $HOME/ORB_SLAM2

RUN perl -0pi -e 's/\ninstall\(\n    EXPORT \$\{PROJECT_NAME\}Targets DESTINATION \$\{CMAKECONFIG_INSTALL_DIR\}\n\)\n/\n/s' CMakeLists.txt && \
    printf '%s\n' \
      '# Compute paths' \
      'get_filename_component( PROJECT_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH )' \
      'SET( ORB_SLAM2_INCLUDE_DIRS "@EXPORT_LIB_INC_DIR@" )' \
      'SET( ORB_SLAM2_INCLUDE_DIR  "@EXPORT_LIB_INC_DIR@" )' \
      '' \
      '# Prefer explicit installed library paths over exported targets so downstream' \
      '# consumers do not need DBoW2/g2o in the same CMake export set.' \
      'SET( ORB_SLAM2_LIBRARIES    "${PROJECT_CMAKE_DIR}/../../libORB_SLAM2.so" )' \
      'SET( ORB_SLAM2_LIBRARY      "${PROJECT_CMAKE_DIR}/../../libORB_SLAM2.so" )' \
      'SET( ORB_SLAM2_CMAKEMODULES @CMAKE_CURRENT_SOURCE_DIR@/../CMakeModules )' \
      > src/ORB_SLAM2Config.cmake.in && \
    sed -i '/#include <thread>/a #include <unistd.h>' src/System.cc && \
    sed -i 's|MapPub->SetCurrentCameraPose(Tcw);|// MapPub removed for headless build|' src/System.cc && \
    sed -i '/#include<mutex>/a #include<unistd.h>' src/LocalMapping.cc && \
    sed -i '/#include<thread>/a #include<unistd.h>' src/LoopClosing.cc && \
    sed -i '/#include <mutex>/a #include <unistd.h>' src/Viewer.cc && \
    sed -i 's/make -j/make -j1/' build.sh && \
    sed -i 's/-DROS_BUILD_TYPE=Release/-DCMAKE_BUILD_TYPE=Release/' build.sh && \
    sed -i '/PYTHON_EXECUTABLE:FILEPATH/d' build.sh

WORKDIR /root/ORB_SLAM2
CMD ["/bin/bash"]
